# Generated by Django 5.0 on 2025-11-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis', '0002_resumeanalysis_suggestions_alter_resumeanalysis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='ats_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='matched_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='missing_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
