# Generated by Django 5.0 on 2025-11-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis', '0003_alter_resumeanalysis_ats_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='analysis_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
